engagement_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: dashboard-project-425723
      dataset: engagement_analytics_dev
      threads: 4
    prod:
      type: bigquery
      method: oauth
      project: dashboard-project-425723
      dataset: engagement_analytics_prod
      threads: 4
